Feat/miniblog
saitamau-maximum/blog-practice pull request #1
Opened 2023-12-10 11:26 UTC by seiei-n

2023-12-10 11:41 UTC, sor4chi requested changes

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +	dbfileName = "../db/db.sqlite3"
```suggestion
const templatePath = "../frontend"

const (
	dbPath = "../db/db.sqlite3"
```

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +	lastInsertID = `SELECT last_insert_rowid() AS id`
いらなさそう

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +	deleteAllPostTable = `DELETE FROM posts`
```suggestion
	createPostTableQuery = `CREATE TABLE IF NOT EXISTS posts (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		title TEXT,
		body TEXT,
		author TEXT,
		created_at INTEGER
	)`
	

	// ブログポストテーブルにデータを挿入するSQL文
	insertPostQuery = `INSERT INTO posts (title, body, author, created_at) VALUES (?, ?, ?, ?)`

	// ブログポストテーブルからデータを取得するSQL文
	selectAllPostsQuery = `SELECT * FROM posts`

	// ブログポストテーブルのデータを更新するSQL文
	updatePostQuery = `UPDATE posts SET title = ?, body = ?, author = ?, created_at = ? WHERE id = ?`

	// ブログポストテーブルのデータを削除するSQL文
	deletePostQuery = `DELETE FROM posts WHERE id = ?`

	// ブログポストテーブルのデータを全削除するSQL文
	deleteAllPostsQuery = `DELETE FROM posts`
```

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +}
```suggestion
var db *sqlx.DB

func dbInit() {
	// ブログポストテーブルを作成
	db.MustExec(createPostTable)
}
```

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +}
```go
db = dbConnect()
defer db.Close()
```
はmainで

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +		createdAt := time.Now().Unix()
バリデーション

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +}
```suggestion
func dbUpdate(id int, title string, body string, author string, createdAt string) error {
	db := dbConnect()
	defer db.Close()

	// ブログポストテーブルのデータを更新
	_, err := db.Exec(updatePostTable, title, body, author, createdAt, id)
	if err != nil {
		return err
	}
	return nil
}
```

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +}
以下同様

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +		log.Fatal(err)
`log.Fatal`は良くないので`log.Print`とかにして、InternalServerErrorを返して早期returnしよう

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +	t, err := template.ParseFiles(Template + "/post.html")
t := template.Must(template.ParseFiles...
のようにしてerror処理を無視して大域へ（こうすることでparseのキャッシュと、parse errorな時はサーバーが立つ前にエラーになる）

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +	http.HandleFunc("/create-post", CreatePostHandler)
ここの`/create-post`、`/post/new`にしたい

2023-12-10 11:41 UTC, sor4chi commented on backend/main.go
> +	db.Get(&post, selectPostTable+" WHERE id = ?", id)
queryをオンデマンドで組み立てるくらいなら最初のクエリリストに`selectPostByIdQuery`クエリでも書こう

2023-12-11 04:37 UTC, seiei-n commented on backend/main.go
> +	dbfileName = "../db/db.sqlite3"
修正しました

2023-12-11 04:38 UTC, seiei-n commented on backend/main.go
> +	lastInsertID = `SELECT last_insert_rowid() AS id`
修正しました

2023-12-11 04:38 UTC, seiei-n commented on backend/main.go
> +	deleteAllPostTable = `DELETE FROM posts`
修正しました

2023-12-11 04:38 UTC, seiei-n commented on backend/main.go
> +		log.Fatal(err)
修正しました

2023-12-11 04:39 UTC, seiei-n commented on backend/main.go
> +	t, err := template.ParseFiles(Template + "/post.html")
修正しました

2023-12-11 04:41 UTC, seiei-n commented on backend/main.go
> +	db.Get(&post, selectPostTable+" WHERE id = ?", id)
修正しました

2023-12-11 04:49 UTC, seiei-n commented on backend/main.go
> +}
修正しました

2023-12-11 04:49 UTC, seiei-n commented on backend/main.go
> +}
修正しました

2023-12-11 04:50 UTC, seiei-n commented on backend/main.go
> +	http.HandleFunc("/create-post", CreatePostHandler)
修正しました

2023-12-11 04:50 UTC, seiei-n commented on backend/main.go
> +		log.Fatal(err)
修正しました

2023-12-11 04:51 UTC, seiei-n commented on backend/main.go
> +		createdAt := time.Now().Unix()
つけました

2023-12-11 05:06 UTC, sor4chi requested changes
これnet/http使うとmethodでの処理分割めんどいな
echo使うことも想定した方がいいかも

2023-12-11 05:06 UTC, sor4chi commented on frontend/create.html
> +    </form>
formにrequiredをつけてバリデーションしましょう

基本的にWebアプリではバリデーションをバックフロントの両方でかけることが推奨されています

2023-12-11 05:06 UTC, sor4chi commented on frontend/post.html
> +<!DOCTYPE html>
共通化できるところは共通化したい
やり方があった気がする（htmlをコンポーネント化するイメージ）

HeadとかHtmlのbody以外はタイトルだけ動的にして共通化みたいなのできなかったかな

2023-12-11 05:06 UTC, sor4chi commented on backend/main.go
> +	db.Get(&post, selectPostByIdQuery, id)
err破棄してない？

2023-12-11 05:06 UTC, sor4chi commented on backend/main.go
> +func dbInsert(title string, body string, author string, createdAt int64) (int64, error) {
関数名がdbInsertだと他のテーブル増えた時にわからなくなりそうだと思った

2023-12-11 05:06 UTC, sor4chi commented on backend/main.go
> +func dbInsert(title string, body string, author string, createdAt int64) (int64, error) {
他も同様

2023-12-11 05:06 UTC, sor4chi commented on backend/main.go
> +	dbInit()
これは全般に言えることだけど、関数名は動詞から始まりそのあと目的語 -> 名詞の方が読みやすいと思う

initDbとかcreatePostHandler

英語わからんけど

2023-12-11 05:26 UTC, seiei-n commented on frontend/post.html
> +<!DOCTYPE html>
できるけど、まだやってない（）
とりまHeadだけ共通化してみる

2023-12-11 06:03 UTC, seiei-n commented on frontend/create.html
> +    </form>
修正しました

2023-12-11 06:03 UTC, seiei-n commented on backend/main.go
> +	db.Get(&post, selectPostByIdQuery, id)
修正しました

2023-12-11 06:03 UTC, seiei-n commented on backend/main.go
> +	dbInit()
修正しました

2023-12-11 06:04 UTC, seiei-n commented on backend/main.go
> +func dbInsert(title string, body string, author string, createdAt int64) (int64, error) {
修正しました

2023-12-11 07:04 UTC, seiei-n commented on frontend/post.html
> +<!DOCTYPE html>
共通化しました

2023-12-11 07:20 UTC, sor4chi requested changes
あと少し
意見あったら反論してもらっていいからね

2023-12-11 07:20 UTC, sor4chi commented on frontend/index.html
> +          >{{.Title}} by {{.Author}} on {{.CreatedAt | date}}</a
この `{{.Title}}` 、headの `{{.Title}}`と被ってる気がする
動作確認までできてないから確証はないけど別にしたいこともあるだろうし、 headの方を`{{.PageTitle}}`とかにした方がいいかもしれない？

2023-12-11 07:20 UTC, sor4chi commented on frontend/layout.html
👍

2023-12-11 07:20 UTC, sor4chi commented on frontend/create.html
> +  <input type="submit" value="作成" />
input type submitよりbutton type submitの方がおそらくみんな混同しなし、スタイリングもやりやすいと思うからそっちの方がいいかも！

2023-12-11 07:20 UTC, sor4chi commented on frontend/create.html
> +<!-- フォームを作成する -->
copilot promptの消し忘れかな？

2023-12-11 07:22 UTC, seiei-n commented on frontend/index.html
> +          >{{.Title}} by {{.Author}} on {{.CreatedAt | date}}</a
Posts配列のTitle参照してるから動きはするけど後々のこと考えてheadの方を変えまする

2023-12-11 07:29 UTC, seiei-n commented on frontend/index.html
> +          >{{.Title}} by {{.Author}} on {{.CreatedAt | date}}</a
修正完了

2023-12-11 07:29 UTC, seiei-n commented on frontend/create.html
> +  <input type="submit" value="作成" />
修正しますた

2023-12-11 07:29 UTC, seiei-n commented on frontend/layout.html
😄

2023-12-11 07:29 UTC, seiei-n commented on frontend/create.html
> +<!-- フォームを作成する -->
消しました

2023-12-11 07:34 UTC, sor4chi approved these changes
OK
あともし体力があれば
```tree
.
├── .gitignore
├── go.mod
├── go.sum
├── db.sqlite3 (ignored)
├── blog-practice (ignored)
├── main.go
└── templates/
    ├── index.html
    ├── layout.html
    ├── create.html
    └── post.html
```

こういうふうにするといいかも

2023-12-11 07:58 UTC, merged